### ISSUE TITLE
DomainController 2 Wait Condition Error

### ISSUE THREAD

**Issue by nsagoo-pivotal** [aws-quickstart/quickstart-microsoft-activedirectory#15]
I am running into a DomainController Wait Condition error when deploying scenario1 of the Cloudformation Stack. The high-level error I receive is `Embedded stack arn:aws:cloudformation:us-east-2:129774511219:stack/Active-Directory-DS-ADStack-15BBY8T0X8B52/b979a2a0-61ed-11e8-8912-50faf8bfacd1 was not successfully created: The following resource(s) failed to create: [DomainController2WaitCondition].` 

Here is an image with more details from the nested stack. 
<img width="1365" alt="screen shot 2018-05-27 at 4 24 57 pm" src="https://user-images.githubusercontent.com/12254224/40590889-12682486-61d5-11e8-891d-c50c463814e3.png">

**Comment by nsagoo-pivotal** [comment]
Here is the template that I am using: 

https://aws-quickstart.s3.amazonaws.com/quickstart-microsoft-activedirectory/templates/ad-master-1.template

**Comment by Fishbowler** [comment]
Have the same problem. Did you ever resolve this?

I had my CF stack not destroy everything on failure, then used SSM run command to get the log.

> Active Directory Domain Services could not create the NTDS Settings object for this Active Directory Domain Controller CN=NTDS Settings,CN=DC2,CN=Servers,CN=AZ2,CN=Sites,CN=Configuration,DC=example,DC=com on the remote AD DC DC1.example.com. Ensure the provided network credentials have sufficient permissions.
> 
> "Could not find the domain controller for this domain."

Looks like perhaps there's a missing step in the setup where DC2 needs DNS pointing to DC1 before it attempts to enrol / dcpromo?

**Comment by Fishbowler** [comment]
^ Nope, not that. Tried that and got the same result.

**Comment by Fishbowler** [comment]
The NetBIOS name being autogenerated must be different what we're manually specifying as part of the install script.

The error above happens when enrolling DC2 using Install-ADDSDC.ps1 which uses the NetBIOS name as part of the username for authentication. Presumably the autogenerated NetBIOS name didn't match, and so authentication failed.

The fix in PR #20 fixes both the parameter being passed to the script, and how it uses it with the Install-ADDSForest cmdlet.

Empirically, this fix works, but regardless, PR #20 feels like a "good" change - that DC1 is created following the explicit user-specified parameters to the template.

**Comment by Fishbowler** [comment]
This went quiet, so I thought I'd come back to add a little more context and explain the error more succinctly, given the context you've provided.

- DC1 is created using Install-ADDSForest without the NetBIOS name, so a computed one is used (as per the docs you linked).
- DC2 is created, and attempts to join the domain using the credentials supplied to template. It fails as the NetBIOS part of the username is incorrect (as this is using the NetBIOS name supplied by the user).
- An error is raised, and the wait condition fails.

PR #20 ensures DC1 is created with the correct NetBIOS name so that DC2 can authenticate.

**Comment by Schizamp** [comment]
Chiming in, am experiencing the same issue. Opened a support case with AWS.

**Comment by Schizamp** [comment]
Followed the issues here and confirm your finding @Fishbowler.
Install-ADDSForest needs to include the parameter for DomainNetBIOSName.

On DC1, it does not reference the $DomainNetBIOSName, which the script even accepts as an input parameter:
Install-ADDSForest -DomainName $DomainDNSName -SafeModeAdministratorPassword (ConvertTo-SecureString $DomainAdminPassword -AsPlainText -Force) -DomainMode Default -ForestMode Default  -Confirm:$false -Force

On DC2, the $DomainNetBIOSName is referenced as the user who is performing the DCPromo:
$DomainAdmin = **_$DomainNetBIOSName_** + "\" + $DomainAdminUser
    $DomainAdminPassword = (Get-SSMParameterValue -Names $SSMParamName -WithDecryption $True).Parameters[0].Value
    Install-ADDSDomainController -InstallDns -DomainName $DomainDNSName -Credential (New-Object System.Management.Automation.PSCredential($DomainAdmin,(ConvertTo-SecureString $DomainAdminPassword -AsPlainText -Force))) -SafeModeAdministratorPassword (ConvertTo-SecureString $DomainAdminPassword -AsPlainText -Force) -Confirm:$false -Force 

Whoever owns the Powershell scripts for this AWS Quickstart needs to update the script for DC1, Install-ADDSForest, to this line:

Install-ADDSForest -DomainName $DomainDNSName **_-DomainNetbiosName $DomainNetBIOSName_** -SafeModeAdministratorPassword (ConvertTo-SecureString $DomainAdminPassword -AsPlainText -Force) -DomainMode Default -ForestMode Default  -Confirm:$false -Force

AWS Cloudformation Support could not replicate the issue, probably because they did not specify a NetBIOS name in the CFT parameters or coincidentally chose one that DC1 defaulted to, like amazon.com.

**Comment by vsnyc** [comment]
Thank you @Fishbowler and @Schizamp, appreciate the details. It looks like PR #20 will fix this, will get that prioritized.

**Comment by vsnyc** [comment]
PR #20 has been merged. I'll resolve this issue, please create a new one if you find any other issues.

**Comment by PJo777** [comment]
Was this ever resolved ?. I am getting an error from the WAIT-Condition.

**Comment by virtlima** [comment]
We just release an update where we are using PowerShell DSC to setup Domain Controllers and AWS Systems Manager. If you try deploying that update and providing feedback it would be greatly appreciated.

**Comment by PJo777** [comment]
Sure....so should we use "AWSQuickstart-ActiveDirectoryDS.yml" ?

**Comment by virtlima** [comment]
The updated [ad-1.template](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/master/templates/ad-1.template) will create that SSM Automation Document for you and launch it. It should work just like the previous Quick Start, except use SSM as opposed to cfn-init and the PowerShell DSC Scripts within the Repo leverage DSC modules to deploy AD ([install-ad-modules.ps1](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/master/scripts/install-ad-modules.ps1), [LCM-Config.ps1](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/master/scripts/LCM-Config.ps1), [ConfigDC1.ps1](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/master/scripts/ConfigDC1.ps1), [ConfigDC2.ps1](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/master/scripts/ConfigDC2.ps1) and [Dns-Config.ps1](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/master/scripts/Dns-Config.ps1)). We are working on updating the deployment guide and officially launching it, I apologize that the deployment guide does not match how the Quick Start Currently Operates.

**Comment by PJo777** [comment]
That template failes with the following error:
The following resource(s) failed to create: [DomainController2]. . Rollback requested by user.

I did not get a chance to capture the exact error, but it seemed like there was an issue in retriving some password.

**Comment by virtlima** [comment]
What Region are you launching this in? Do you have access or the ability to leverage [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/)? We currently generate some passwords with Secrets Manager, as well as store the Password you specify in secrets manager.  If you can provide the error message that would be greatly appreciated.

**Comment by virtlima** [comment]
I re-Opened this to track the last issue you mentioned, currently looking into it now... Keep you posted. In the interim please post any errors you may get.

**Comment by virtlima** [comment]
I re-ran a test and was not able to replicate the issue on Domain Controller 2. The Name Tag value you specified, is it the same as other EC2 Instances in your environment? I.E. do you have more than the two instances deployed by the Quick Start named DC1 and DC2? If so, can you try again naming the Instances DC-1a and DC-2a instead and let me know the result? The SSM automation document is dependent on the Name tag value to pull the instances it will run scripts on. When it runs in your environment I am wondering if it pulling more than the ones deployed by the Quick Start.

**Comment by virtlima** [comment]
Closing this Issue, unable to replicate issue, we not provide a SSM set of templates for regions that do not have Secrets manager.

**Comment by smolnik** [comment]
It wasted my long hours (10 attempts) for various options - simply put ADStack-1 does not work at all. Got stuck:
CREATE_IN_PROGRESS | AWS::EC2::Instance | DomainController2

**Comment by smolnik** [comment]
The issue with stuck DC 2 likely occurs when you use password missing requirement of the password policy. You cannot use e.g. username in the password. E.g. user: Admin and password Admin12xrfD!#.

**Comment by smolnik** [comment]
It causes the entire CF stack get stuck.

**Comment by virtlima** [comment]
@smolnik Where you able to get this deployed? Or still Experiencing Issues?

**Comment by smolnik** [comment]
Yes, I were able... Just after I've changed the password from Admin12xrfD!# (example) to e.g. AdCmFXan122. Likely, "Admin" was the part of the password phrase and user name simultaneously - looks like it fell against some DC policy, I suppose. After the password change, CF stack has been deployed seamlessly. I had analyzed logs in CloudWatch Logs and noticed the exception on violating password policy. You may easily try to replicate the issue.

**Comment by virtlima** [comment]
Currently working on replicating, will try and add a note in the deployment guide about password complexity. In the Quick Start we are not modifying any password policy in AD, this maybe a default policy.
