### ISSUE TITLE
CFN Create fails with error - Parameter 'PKI' must be one of AllowedValues

### ISSUE THREAD

**Issue by shankara-n** [aws-quickstart/quickstart-microsoft-activedirectory#170]
## Detailed Repro Steps:
Go to launch wizard at https://us-east-2.console.aws.amazon.com/launchwizard/home?region=us-east-2#deployment/MicrosoftActiveDirectory
Make following selections and hit "Create Deployment"
2.1 Available workloads - Microsoft Active Directory
2.2 Deployment type - Self Managed AD (new VPC)
Select 'Two tier' for PKI, select anything for other fields
Track Deployment events in cloud formation

## Expected Result
Deployment succeeds

## Actual Result
Deployment fails with error CREATE_FAILED Parameter 'PKI' must be one of AllowedValues

**Comment by vsnyc** [comment]
@relmota - this is caused by this change:
https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/commit/93ce613854d5c18a792b226697ae9d63522a6000#diff-b6f8e1eecc7a4a7279e59b6235f361e1f151f0d3905cdc7dec0437ad34d3fee7L341

Could you change the allowed values list back to `Two-Tier` in https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/main/templates/ad-1.template.yaml#L346-L351?
