### ISSUE TITLE
Error in ad-2.template

### ISSUE THREAD

**Issue by Fedora-Man** [aws-quickstart/quickstart-microsoft-activedirectory#40]
ad-2.template line 396:
"Get-NetAdapter | Set-DnsClientServerAddress -ServerAddresses $netip.DNSServer.ServerAddresses;",

This sets the DNS to AWS default DNS it should be:
"Get-NetAdapter | Set-DnsClientServerAddress -ServerAddresses $netip.IPv4Address.IpAddress;"

To setup the AD DNS to the AD IP Address!

**Comment by virtlima** [comment]
We will look into this.

**Comment by davmayd** [comment]
The ad-2 template does not promote the new servers to domain controllers, since it's dependent on connectivity to an Active Directory environment at another location. Per the deployment guide, once this scenario is deployed the person deploying it should establish connectivity with their on-premises Active Directory environment and then manually promote the servers to domain controllers. Since they are not yet domain controllers they should not have their local IP addresses used as DNS server IP addresses.
